- resources/assets/js/Admin/FieldRegistry.js
- resources/assets/js/Admin/Fields/Slug.js
- resources/assets/stylesheets/layout/fields.scss
- src/Admin/Form/Fields/AbstractField.php
- src/Admin/Form/Fields/Renderer/TranslatableFieldRenderer.php
- src/Admin/Form/Fields/Slug.php
- src/Admin/Form/Fields/Translatable.php
- src/Admin/Traits/Crudify.php
- src/Http/Controllers/Admin/NodesController.php
Make slug translatable:
`$form->addField(new Translatable((new Slug('slug', 'name', $this->url('api', 'slug_generator')))->rules('required')));`
And:
1. Do not regenerate slug on blur every time - only when creating object for the first time.
2. Do not append random id if it is not necessary.
> Make slug translatable

- src/Repositories/ArboryFilesRepository.php
Same as https://github.com/arbory/arbory/pull/33, but for 0.1 branch.
> keep file extension if available when getting free filename

- resources/assets/js/Admin/FieldRegistry.js
- resources/assets/js/Admin/Fields/Slug.js
- resources/assets/stylesheets/layout/fields.scss
- src/Admin/Form/Fields/AbstractField.php
- src/Admin/Form/Fields/Renderer/TranslatableFieldRenderer.php
- src/Admin/Form/Fields/Slug.php
- src/Admin/Form/Fields/Translatable.php
- src/Admin/Traits/Crudify.php
- src/Http/Controllers/Admin/NodesController.php
Same as https://github.com/arbory/arbory/pull/32/files but for 0.1 branch.
> make slug translatable and improve uniqueness check

- resources/assets/js/Admin/Fields/File.js
Sames as https://github.com/arbory/arbory/pull/89 but for 0.3 branch.
> unset ArboryFile remove indicator if input changed

- database/migrations/2018_11_27_152132_add_indexes_to_files_table.php
Reference to https://github.com/arbory/arbory/issues/67
> Added unique index for files on id

- database/migrations/2018_11_21_145223_add_indexes_to_nodes_table.php
Reference to https://github.com/arbory/arbory/issues/68
> Nodes table

- database/migrations/2019_01_09_101302_add_activation_columns_to_nodes_table.php
- src/Nodes/Node.php
* Added Data transfer to migration
* Added missing PHPDoc
> Migrate active to activated_at data when changing Node Activation

- composer.json
- src/Admin/Exports/DataSetExport.php
- src/Admin/Exports/ExportInterface.php
- src/Admin/Exports/Type/ExcelExport.php
- src/Admin/Exports/Type/JsonExport.php
- src/Admin/Grid/ExportBuilder.php
- src/Admin/Traits/Crudify.php
Add column names to XLSX export
Make JSON export as BinaryFile not HTTP response
Remove Excel dependancy from Crudify
> Module export improvements

- src/Admin/Form/Fields/Select.php
Added back support to relationship based selects which was removed in #122
> Reimplemented support to relationship based selects

- src/Admin/Traits/Crudify.php
When creating a new resource you will be redirected to resource edit page instead of resource grid page
> Fixed redirect url when creating new resource

- resources/assets/js/Admin/Fields/Sortable.js
Fixes broken position field values when there are nested hasMany fields
> Fixed nested hasMany sortable behaviour

- resources/assets/js/Admin/Fields/Sortable.js
Fixed sortable buttons go 2x times down or up when have nested sortable!
> Fixed nest sortable buttons

- config/arbory.php
- resources/lang/en/security.php
- resources/views/controllers/security/login.blade.php
- resources/views/layout/login.blade.php
- resources/views/layout/main.blade.php
- src/Http/Controllers/Admin/SecurityController.php
- src/Http/Requests/LoginRequest.php
**Refactoring login page:**
1. Add translation
2. Create a separate login layout
3. Fix validation attributes names
> Refactoring login 1.0

- resources/assets/stylesheets/layout/notifications.scss
- resources/views/layout/login.blade.php
- resources/views/layout/main.blade.php
- resources/views/layout/partials/message.blade.php
Able show flash message! 
Usage:
1. Success message: `session()->flash('success', 'Welcome!')`
2. Error message `back()->withError($validator)`
> Refactoring flash message

- src/Admin/Grid.php
- src/Admin/Grid/Builder.php
- src/Admin/Grid/Row.php
Can disabled or enable toolbox (three dots) from the grid! Default toolbox is enabled. 
Code
`$grid->toolbox(false/true)`
> Can disabled or enable toolbox from grid!

- src/Http/Middleware/ArboryRouteRedirectMiddleware.php
> Fix redirect

- src/Http/Middleware/ArboryRouteRedirectMiddleware.php
> Fix redirect status

- src/Http/Controllers/Admin/RedirectsController.php
Fixing the Redirect controller.
> Fixing redirect controller

- .gitignore
- composer.json
- composer.lock
`^` will install up to (but not including) laravel 6
> Fix dependencies and version constraints 

- .gitignore
- composer.json
- composer.lock
- src/Admin/Filter/Parameters/ParameterTransformerPipeline.php
Fixes comparability with laravel 5.6 and 5.5, `thenReturn` is only available as of 5.7
> Fix laravel compatibility

- src/Admin/Grid/Filter.php
When searching on the admin panel, some Latvian words like "Kristīne",  then shows MySQL error.
> Convert search string to ascii

- .gitignore
- .travis.yml
- composer.json
- phpunit.xml
- tests/Admin/Form/Fields/Renderer/FileSizeTest.php
- tests/Html/Elements/ElementTest.php
- tests/Services/FieldSetFieldFinderTest.php
Update composer.json dev dependency versions
Add .ignore rules
Fix tests
Remove deprecated argument in phpunit.xml
> Update phpunit and phpunit-pretty-printer version

- resources/assets/js/Admin/AdminPanel.js
- resources/assets/js/include/remote_validator.js
- src/Admin/Form/Fields/ObjectRelation.php
- src/Admin/Form/Fields/Renderer/AssociatedSetRenderer.php
- src/Admin/Form/Fields/Renderer/ObjectRelationRenderer.php
- src/Admin/Module/ResourceRoutes.php
- src/Menu/Menu.php
- src/Providers/NodeServiceProvider.php
- src/Support/Translate/Translatable.php
Fix issues related to incomplete data configuration/setup
> Small stability fixes

- src/Admin/Form/Fields/Slug.php
Fixes node preview URL for inactive nodes.
> Fix node preview URL

- config/arbory.php
- database/factories/ArboryFileModelFactory.php
- database/factories/NodeFactory.php
- resources/assets/stylesheets/environment/variables/dimensions.scss
- resources/assets/stylesheets/layout/grid.scss
- resources/assets/stylesheets/vendor/magnific-popup/main.scss
- src/Files/ArboryFile.php
- src/Html/Elements/Element.php
- src/Menu/Menu.php
- src/Nodes/Node.php
- src/Services/SettingRegistry.php
- Added ArboryFile database factory
- Settings relationship eagerloading config
> Add arbory file model factory, setting relations config

- .gitignore
- database/factories/Files/ArboryFileModelFactory.php
- database/factories/NodeFactory.php
- database/factories/Nodes/NodeFactory.php
- src/Files/ArboryFile.php
- src/Nodes/Node.php
* Removes nonexistent `include_in_sitemap` attribute from Node factory
* Aligns factory paths with model paths
> Fix node model factory

- src/Admin/Form/Fields/Renderer/FileFieldRenderer.php
Added missing classes to ArboryFile field to fix delete button not working
> Fix js for ArboryFile field

- src/Nodes/Node.php
Adds missing phpdocs for Node model properties to help with static analysis.
> Document Node model properties
