arbory/arbory

- src/Admin/Form/Fields/Renderer/DateFieldRenderer.php
`date( 'Y-m-d H:m', strtotime( $value ) )` changed to `date( 'Y-m-d H:i', strtotime( $value ) )` to get hours and minutes instead of hours and months
> date representation format in DateFieldRenderer class fixed

- config/arbory.php
- resources/views/layout/main.blade.php
env() functions usage outside config file is not advised. This may lead to empty env values.
More info: 
[https://laravel.com/docs/5.4/configuration#configuration-caching](url)
> If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files.
> [googleMaps]: retrieve api key from config

- src/Repositories/ArboryFilesRepository.php
Fixes issue described in https://github.com/arbory/arbory/issues/16
> keep file extension if available when getting free filename

- resources/assets/js/Admin/Fields/MapCoordinates.js
Currently MapCoordinates field is only working using name `coordinates`. This fix allows using custom name.
> MapCoordinates: allow custom name

- src/Admin/Settings/SettingDefinition.php
- src/Admin/Settings/Settings.php
At the moment, translatable Setting always uses the locale which was active at the time of calling Arbory\Base\Services\SettingRegistry::importFromDatabase. That creates a problem if locale is changed afterwards.
> For translatable Setting, resolve its locale at the time of its usage

- src/Admin/Settings/Settings.php
Whenever translatable setting was null, get method was throwing with message `Call to a member function getAttribute() on null`
> Fix get method of Settings class

- resources/assets/js/Admin/Fields/RichText.js
CKEditor expects JSON response but Laravel File Manager is sending script by default. For more information, see https://github.com/UniSharp/laravel-filemanager/pull/474
> Bugfix of LFM response type: case of successful upload

- resources/assets/js/Admin/Fields/RichText.js
- routes/admin.php
- src/Http/Controllers/Admin/UploadController.php
- src/Http/Middleware/ArboryAdminModuleAccessMiddleware.php
- src/Providers/ArboryServiceProvider.php
CKEditor expects error response of following structure:
`[
'uploaded': 0,
'error': [
'message': someText
] 
]`
But LVM is sending just an array of error messages:
`[msg1, msg2, ...]`
This PR overrides LFM UploadController to correct that behaviour.
> Bugfix of LFM response structure: case of unsuccessful upload

- resources/assets/js/Admin/Fields/File.js
Fixes error where a resource.content.file.remove=1 parameter is needlessly submitted. Error occurs in the following scenario:
1. A file is added and successfully submitted to an ArboryFile form field input.
2. File input is cleared (using X button) without submitting the form or reloading the page.
3. A new file is added to the file input.
4. Form is submitted.
> Fix error after submitting previously cleared ArboryFile file input 

- src/Providers/ArboryServiceProvider.php
When Role don't have permission for custom module, it is removed from menu, but is still accessible unless Middleware is added.
> Add AdminModuleAccess middeware to all admin routes

- src/Repositories/NodesRepository.php
Fixes exception caused by an invalid column being queried when using NodesRepository to fetch active nodes. 
Should have been updated to use the active scope together with https://github.com/arbory/arbory/pull/99
> fix incorrect query condition for active nodes

- config/arbory.php
- src/Admin/Form/Fields/Slug.php
- src/Nodes/ContentTypeRoutesRegister.php
Fixes issue caused by a typo where hashed slug generated in admin Slug is different from the one registered in ContentTypeRoutesRegister. Gets salt value from config instead.
Additionally, adds config value to enable/disable preview functionality globally to avoid potential issue where pages could be previewed without configuring salt.
> Fix node preview slug hash mismatch

- src/Admin/Form/Fields/Renderer/AssociatedSetRenderer.php
Fixes bug where clicking on labels within an associated items list (BelongsToMany field) doesn't toggle the related checkbox.
> Add id and for attributes to checkboxes and labels in associated set

- src/Admin/Form/Fields/BelongsToMany.php
Fixes bug where pivot table holding relations data would be updated with new duplicate entries on each save when using BelongsToMany field. 
Without the fix, existing ids with a int type are being strictly compared to submitted ids with a string type, causing the `!in_array` check to always evaluate as true.
> Remove type check when comparing submitted with existing ids

- src/Admin/Form/Fields/Deactivator.php
Extend Deactivator field from Checkbox field because it basically is a checkbox with specific logic added on top.
Fixes an error caused by getCheckedValue method not being found when Deactivator field is being rendered by CheckBoxFieldRenderer.
> Extend Deactivator from Checkbox field

- src/Admin/Form/Fields/Renderer/Styles/Options/StyleOptions.php
Fixes the following error caused by a missing return statement.
```
Return value of Arbory\Base\Admin\Form\Fields\Renderer\Styles\Options\StyleOptions::addAdditional() must implement interface Arbory\Base\Admin\Form\Fields\Renderer\Styles\Options\StyleOptionsInterface, none returned
```
> Add missing return statement to fulfill interface

- src/Admin/Grid.php
- src/Admin/Grid/Column.php
Allows to change the default grid click url to anything
```
$grid->setRowUrlCallback(function(Model $model) {
return 'new url';
return null; // Empty values will not make the cell clickable
});
```
> Added support for overridable grid URLs

- database/migrations/2017_06_07_113300_modify_primary_key_in_settings_table.php
Fix issue with settings table migration where on latest MariaDB version (10.4) it would cause an access violation error with incorrect index name when changing unique index to primary.
> Fix migration bug for settings table

- src/Admin/Constructor/Models/ConstructorBlock.php
- stubs/pages.stub
**Expected:** You can open the page after saving
**Actual:** Error is returned 
`Call to undefined relationship [block] on model [Arbory\Base\Admin\Constructor\Models\ConstructorBlock]. `
This fixed above mentioned issue.
> Fix issue when adding new constructor block to constructor node

- src/Admin/Form/Fields/Renderer/ConstructorFieldRenderer.php
When adding new constructor fields, users are given an option to choose between basically either class names of the block or some snake_cased values (depending on how You implement it). 
This takes use of BlockInterface title() method in order to display something readable :)
> Add readability to constructor 

- src/Admin/Form/Fields/Renderer/IconPickerRenderer.php
Right now IconPicker ignores all paths after the first one. This is an unnecessary limit and doesn't work for complex SVGs.
> Allow multiple paths for SVG icons

- src/Admin/Form/Fields/Link.php
Fixes https://github.com/arbory/arbory/issues/208
Issue caused by attempting to iterate over Link sub-fields (href, title, new_tab) incorrectly.
> Fix "Method does not exist" error on opening form with Link field

- resources/assets/stylesheets/layout/nodes.scss
- src/Nodes/Admin/Grid/Renderer.php
- src/Nodes/Node.php
Opening node grid with too many nodes the page in unusable because every single node is checking if their parent nodes are active. Improve speed by only checking the node itself and use css to achieve the same styling as previously.
> Improve active node check and display speed for controller view

- src/Providers/TranslationServiceProvider.php
After replacing Illuminate\Translation\TranslationServiceProvider::class with \Arbory\Base\Providers\TranslationServiceProvider::class in config/app.php and attempting command 'cumposer dumpautoload' 
> Illuminate\Contracts\Container\BindingResolutionException  : Target class [cache] does not exist.
Seems to be related to laravel 5.8 update https://github.com/laravel/framework/issues/27804
> Fix translation service provider to work with laravel 6

- resources/assets/js/Admin/Fields/Sortable.js
Removes unnecessarily strict `>` from selector for finding position input in sortable fields. Calling `first()` on results should already return the closest descendant. 
The change is needed to fix sortable behaviour for fields rendered via `ConstructorLayout`, or other custom layouts where it's not easily possible to render the hidden position input as a direct descendant of the field's container.
> Fix sortable ui logic for constructor fields

- src/Admin/Constructor/ConstructorLayout.php
Adds support for using non-default column for ordering constructor blocks. Currently, `setOrderBy() / sortable()` calls on constructor field are not fully respected in `ConstructorLayout`.
> Apply orderBy from field in constructor layout

- src/Http/Controllers/Admin/RedirectsController.php
Currently, there are no validation rules set for status field, but submitting the form without selecting status throws an error:
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'status' cannot be null (SQL: insert into `redirects` (`from_url`, `to_url`, `status`, `updated_at`, `created_at`) values (example.test, example.test, ?, 2021-01-09 23:25:32, 2021-01-09 23:25:32))
```
Fix adds required rule to status field.
> Fix error on save in Redirects module

- src/Http/Controllers/Admin/UsersController.php
It's impossible to create a new admin user, because an error is thrown in `UsersController` form, caused by passing unsaved User model to a method which calls `$user->getUserId()`. User model implements `Cartalyst\Sentinel\Users\UserInterface`, which expects `$user->getUserId()` to return int.
```
Return value of Cartalyst\Sentinel\Users\EloquentUser::getUserId() must be of the type int, null returned
```
Fix checks if User exists first.
> Fix new user create error

- src/Files/ArboryFileFactory.php
There is a method name change in Laravel versions (both supported by Arbory 1.0 version) in Illuminate\Database\Eloquent\Relations\BelongsTo class, namely, method getQualifiedForeignKey name is changed to getQualifiedForeignKeyName. Since Arbory 1.0 version uses former method name in ArboryFileFactory class, this fix ensures compatibility for both these Laravel versions.
> Fix support for 5.6 and 5.8 laravel versions in ArboryFileFactory

- composer.json
- composer.lock
- src/Support/ExtendedFluent.php
Starting with Laravel 11.x, two new methods —`set` and `has` — were introduced, which until now were defined in Arbory’s `ExtendedFluent` class. Because these methods cause compatibility issues with the parent class, they have been removed entirely.
> Remove conflicting methods from ExtendedFluent class
